### PR TITLE
Upgrade to latest frontend-auth.

### PR DESCRIPTION
**Pull request by douglashall**

### CODE REVIEW

**Comment by douglashall** [comment]
@iloveagent57 @schenedx @reillz10 This should get the CSRF token auto-retrieval working and improve the login experience by redirecting to the login page before rendering the app if the user is not already authenticated.

**Comment by schenedx** [comment]
@douglashall Does this change solve the issue with POST when we trying to override grades? Also, the auth don't work on `cohort` GET api call. I don't know if that's related.

**Comment by reillz10** [comment]
Handled this with PR #23 so we didn't have to resolve package-lock.json conflicts by hand.

**Comment by douglashall** [comment]
@reillz10 Thanks!

**Pull request closed without merging**
